version: '3'

services:

  mysql:
     image: mysql:5.7
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: prisma
     volumes:
       - mysql:/var/lib/mysql

  prisma:
    image: prismagraphql/prisma:1.27
    restart: always
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: mysql
            host: mysql
            port: 3306
            user: root
            password: prisma
            migrations: true

  server:
    image: bluechords_server
    restart: always
    ports:
      - "4467:4467"
    environment:
      - PRISMA_ENDPOINT=http://prisma:4466

  web:
    image: bluechords_web
    restart: always
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=songchords.net
      - NGINX_PORT=80

volumes:
    mongo:
