version: '3'

services:

  mongo:
    image: mongo:3.6
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: prisma
      MONGO_INITDB_ROOT_PASSWORD: prisma
    volumes:
      - mongo:/var/lib/mongo

  prisma:
    image: prismagraphql/prisma:1.25
    restart: always
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: mongo
            uri: mongodb://prisma:prisma@mongo

  server:
    image: bluechords_server
    restart: always
    ports:
      - "4467:4467"
    environment:
      - PRISMA_ENDPOINT=http://prisma:4466

  web:
    image: bluechords_web
    restart: always
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=songchords.net
      - NGINX_PORT=80

volumes:
    mongo:
