version: '3'

services:

  mongo:
    image: mongo:3.6
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: prisma
      MONGO_INITDB_ROOT_PASSWORD: prisma
    #ports:
    #  - "27017:27017"
    volumes:
      - mongo:/var/lib/mongo

  prisma:
    image: prismagraphql/prisma:1.25
    restart: always
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: mongo
            uri: mongodb://prisma:prisma@mongo

  server:
    build:
      context: ./server
    ports:
        - "4467:4000"
    environment:
        PRISMA_URL: "prisma:4466"
    #volumes:
    #  - ./server:/usr/src/app

volumes:
    mongo:
