version: '3'

services:

    web:
        image: bluechords_web
        restart: always
        ports:
         - "80:80"
        environment:
             - NGINX_HOST=songchords.net
             - NGINX_PORT=80
