version: '3'

services:

  mysql:
     image: mysql
     restart: always
     ports:
       - 3306:3306
     environment:
       - MYSQL_ROOT_PASSWORD=prisma
       - MYSQL_DATABASE=bc
       - MYSQL_USER=bc
       - MYSQL_PASSWORD=bc
     volumes:
       - mysql:/var/lib/mysql

volumes:
    mysql:
